---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - backup.infracloud-citadel-vbakup.com
  resources:
  - volumebackups
  - volumerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.infracloud-citadel-vbakup.com
  resources:
  - volumebackups/finalizers
  - volumerestores/finalizers
  verbs:
  - update
- apiGroups:
  - backup.infracloud-citadel-vbakup.com
  resources:
  - volumebackups/status
  - volumerestores/status
  verbs:
  - get
  - patch
  - update
