# This rule is not used by the project kube-application-snapshot itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the backup.infracloud-citadel-vbakup.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-application-snapshot
    app.kubernetes.io/managed-by: kustomize
  name: volumebackup-editor-role
rules:
- apiGroups:
  - backup.infracloud-citadel-vbakup.com
  resources:
  - volumebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.infracloud-citadel-vbakup.com
  resources:
  - volumebackups/status
  verbs:
  - get
