# This rule is not used by the project kube-application-snapshot itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to backup.infracloud-citadel-vbakup.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-application-snapshot
    app.kubernetes.io/managed-by: kustomize
  name: volumerestore-viewer-role
rules:
- apiGroups:
  - backup.infracloud-citadel-vbakup.com
  resources:
  - volumerestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.infracloud-citadel-vbakup.com
  resources:
  - volumerestores/status
  verbs:
  - get
